### ISSUE TITLE
Problem with handing in "The Missing Courier" pt. 2, in Feralas

### ISSUE THREAD

**Issue by dooooug** [elysium-project/bug-tracker#299] opened 2018-01-09 23:24 UTC
**Server:** Nighthaven
**Patch:** 1.4
**Current behavior:** Clicking on the Wrecked Row Boat at 46:66 in Ferals only shows a "_Greetings XX_" message instead of letting the player hand in the quest.
**Expected behavior:** Clicking on afforementioned boat should let the player hand in "_The Missing Courier_" pt.2 to and give him the following quest, "_Boat Wreckage_".

**Comment by Jaxrs** [comment] 2018-01-09 23:25
There's another boat underwater you might wanna check out.

**Comment by Terranzin** [comment] 2018-01-10 09:00
It´s working correct, you´re at the wrong boat. Duplicate of https://github.com/elysium-project/bug-tracker/issues/66

**Closed by Terranzin** 2018-01-10 09:00 UTC
Labels: Duplicate
