### ISSUE TITLE
Horde are not flagged for PvP in EPL?

### ISSUE THREAD

**Issue by Stoley** [elysium-project/bug-tracker#99] opened 2017-11-28 21:34 UTC
> Singleton - Today at 4:07 PM
> Why aren't Horde flagged for PvP in EPL?
> I have the flag as an Alliance.
> But all the Horde I see are unflagged.

**Comment by Navashed** [comment] 2017-11-29 19:25
Unable to reproduce.

![4ba83243f2ffefb86f48520f6d257c4c](https://user-images.githubusercontent.com/2709545/33394686-1f50e09e-d511-11e7-8307-97cd950a54a3.jpg)

**Comment by Terranzin** [comment] 2017-11-30 08:55
Can´t be reproduced, closing the issue.

**Comment by Stoley** [comment] 2017-11-30 23:34
Proof:
https://cdn.discordapp.com/attachments/377099887973761024/385935855958884354/WoWScrnShot_120117_003047.jpg

**Comment by Navashed** [comment] 2017-12-04 03:26
Confirmed.

Entering EPL did not flag Horde player as should occur when entering contested territory.
Flagged Horde player became unflagged in EPL.

Area appears limited to EPL. Flagging works correctly in WPL and Stratholme area.

EPL is correctly marked as a "Contested Territory" for Horde. The zone appears to be behaving according to PvE server rules.

**Closed** 2018-02-20 17:52 UTC
Labels: Changelog, Fixed
