### ISSUE TITLE
Raene's Cleansing Q bugged

### ISSUE THREAD

**Issue by WuMingi** [elysium-project/bug-tracker#605] opened 2018-03-31 07:39 UTC
After killing Dal Bloodclaw and going to Krolg in furbolg form, he's supposed to hand you the skull back for the final return of the chain. This is bugged however, and the skull does not appear. Hence you can't complete the chain that has very good rewards.

**Comment by YaboyJimmyrustle** [comment] 2018-04-07 23:05
For the second to last turn in for Raene's Cleansing you kill Ran Bloodtooth and 4 Guards. For the last turn in you need to travel North into the set of Furbolg camps to Kill Dal Bloodclaw for his skull, then you return to Astranaar to turn the quest into Raene Wolfrunner.

**Comment by YaboyJimmyrustle** [comment] 2018-04-07 23:14
I apologize for the mess of tags and reopen/closing it. I had a misunderstanding, but the quest is functioning as intended. The skull is never taken from you bags and you are able to turn the quest into Raene Wolfrunner without issue.

**Closed by YaboyJimmyrustle** 2018-04-07 23:14 UTC
Labels: Invalid
