### ISSUE TITLE
Warrior's ability "Slam" is interrupted by damage

### ISSUE THREAD

**Issue by wmuadib** [elysium-project/bug-tracker#774] opened 2018-06-10 05:54 UTC
The title says it all, when you take some damage while casting slam the bar is knocked back a bit just like regular spells.
I have to say that I didn't remember it working like  that, and the sources I can find on the internet seems to indicate that it should NOT be interrupted by damage.
source : http://vanilla-wow.wikia.com/wiki/Slam
(first paragraph)
If it was indeed working like that in vanilla, then please excuse me for posting this useless issue :)
thanks

**Comment by Thenari** [comment] 2018-06-10 06:47
Hey nice an issue i can totally tag my new button "unsure if blizz-like" ;P

Yeah idk much about non magic casting honestly didnt even know its a thing. Ill talk to some old warriors about it they played vanilla a decade ago and are Nerds! Bylat!

**Comment by Thenari** [comment] 2018-06-10 06:51
(Also almost every issue posted is a "useless issue" y'all entitled kids thinking you deserve a not broken game for free ;P)

**Comment by wmuadib** [comment] 2018-06-10 13:41
Thank you Thenari for your swift answer on a sunday :)
I can't wait to hear what your warrior buddys have to say about it.

**Comment by Crusaderz** [comment] 2018-06-13 13:59
[Patch 1.1](http://wowwiki.wikia.com/wiki/Patch_1.1.0) Slam: Available in all Stances, damage reduced, casting is pushed back when hit.
[Patch 2.0.3](https://wow.gamepedia.com/Patch_2.0.3) "[Slam]'s" swing time is no longer slowed by damage taken.

**Comment by Navashed** [comment] 2018-06-25 23:09
Crusaderz is correct. This behavior is Blizzlike, not a bug.

**Comment by Thenari** [comment] 2018-06-26 17:35
Alright so im closing this, good hustle team.

**Closed by Thenari** 2018-06-26 17:35 UTC
Labels: Unsure if blizz-like or a bug
