### ISSUE TITLE
Follow Bug

### ISSUE THREAD

**Issue by SmokealotapotimuS** [elysium-project/bug-tracker#189] opened 2017-12-14 03:07 UTC
Hello! I hadn't seen anything posted about this so I though I'd make my own. Recently my buddies and I started playing on Elysium that we all set up through this link:
https://metawow.com/Thread-Guide-How-to-start-playing-on-Nostalrius-Elysium-relaunching-Vanilla-WoW-server 

Strangely about 50% of us have a follow bug where our character basically runs in the same direction meagerly attempting to turn in the direction of the target you're following. The only other post I found about this was here. 
https://forum.elysium-project.org/topic/55657-follow-bug/

I'm not even sure if that is on the most recent Elysium servers tbh but the video clips in that link are exactly the bug 50% of our friend group (only like 5 people) are encountering. We all installed approx. the same time (within a few days.) The portion of us that haven't encounter this bug used a different install link, I therefore reinstalled with the link they used, sure it would fix the problem, no luck. I've deleted the WDB folder, I've tried the command /console reloadui still no luck.

I also made a ticket basically having my fingers crossed the GM had some bright ideas, which they had a few but unfortunately, still no luck. 

It's not a huge issue but over the course of questing to 60 with other people having to wait on me to take a cig break or use the restroom ect. I'm wasting an enormous amount of my friends and my own time. If anyone has encounter this before or has a fix I would be eternally grateful.

Sincerely, 

One Fat Nerd.

**Comment by Navashed** [comment] 2017-12-14 20:25
Unable to reproduce this issue.

Sorry, no idea what that could be about.

**Comment by SmokealotapotimuS** [comment] 2017-12-15 00:08
Yeah if anyone thinks of a solution worth trying I'd be happy to try it out! Until then i'll just be auto-running into walls I suppose, RIP.

**Comment by SmokealotapotimuS** [comment] 2017-12-15 00:29
My hunch is there is a setting somewhere or a file that needs editing that's somehow conflicting with the follow function but have no idea what that setting or file could be.

**Comment by SmokealotapotimuS** [comment] 2017-12-15 00:43
I think i may have figured it out, when i use the defualt rez my follow function works properly, when I used 1920X1080 my follow function bugs out.

**Comment by SmokealotapotimuS** [comment] 2017-12-15 00:53
I've tested it further and at least for me, following works on every rez but 1920X1080 so at least I know how to get it when i need it! Hopefully this helps ya'll figure out why its doing that. Honestly surprised more people didn't run into this issue.

**Comment by Terranzin** [comment] 2017-12-15 19:32
This isn´t a server error more of a client error which we can´t do much about. Closing the issue.

**Closed by Terranzin** 2017-12-15 19:32 UTC
