### ISSUE TITLE
Zeppelins bugged between Durotar and Tirisfal Glades

### ISSUE THREAD

**Issue by voranir** [elysium-project/bug-tracker#400] opened 2018-02-07 02:33 UTC
- Affecting Nighthaven PvP server, current and all previous patches

- Behavior: When zoning between Durotar and Tirisfal Glades riding the zeppelin, it always flags you for PvP (in both directions). On occasion, it will also instant-kill you when you load after zoning on the zeppelin, and return you to the graveyard alive. Additionally, if you are PvP killed right after zoning from Durotar it will spawn you in the Brill graveyard as a ghost, and then instant kill you while you are already dead. In both cases, the player takes a 10% durability loss from death due to "falling." From my experience, I have been killed and taken durability loss twice, both times when coming from Durotar into Tirisfal Glades. I have not personally experienced the death when going from Tirisfal Glades into Durotar, but the PvP flag still occurs.

- Expected behavior: This zeppelin is not supposed to flag you for PvP, as you are travelling from one safe zone to another. In classic Vanilla, it did not flag you. Also should not be dying as a ghost.

![bug](https://user-images.githubusercontent.com/36216040/35895398-40f9807a-0b85-11e8-9e4c-fc4cd213e18b.PNG)

**Comment by Terranzin** [comment] 2018-02-07 19:40
Duplicate of: https://github.com/elysium-project/bug-tracker/issues/53

**Comment by voranir** [comment] 2018-02-07 19:42
The death portion is not covered in that report

**Comment by sidsukana** [comment] 2018-02-15 09:05
Will be fixed in next update

**Closed** 2018-02-20 17:51 UTC
Labels: Changelog, Fixed

**Comment by voranir** [comment] 2018-03-01 03:23
Bug is back, flagging on zeppelin again.
