### ISSUE TITLE
RE : Stronghold not working with 1h

### ISSUE THREAD

**Issue by Maggrokh** [elysium-project/bug-tracker#350] opened 2018-01-21 11:44 UTC
https://gyazo.com/38b2d20d2de511a1fe93ddada638a21a , really disappointed you close my previous one without really trying .

**Comment by Terranzin** [comment] 2018-01-21 12:34
We used a 1h weapon and the disarm says "Immune" see picture

![image](https://user-images.githubusercontent.com/25831382/35194195-c5fbfc7c-feaf-11e7-86a5-328d5fe1838b.png)

**Comment by Maggrokh** [comment] 2018-01-21 13:15
come to me now and disarm me if you re a gm

**Comment by Terranzin** [comment] 2018-01-21 16:09
Duplicate of: https://github.com/elysium-project/bug-tracker/issues/344 & https://github.com/elysium-project/bug-tracker/issues/191

**Comment by Terranzin** [comment] 2018-01-21 19:36
There´s probably a difference between PTR and Nighthaven, devs will need to look into this.

**Comment by Maggrokh** [comment] 2018-01-27 02:32
New issue :( got disarmed when using weapon chain https://gyazo.com/68da83b969b42342d9c13edc13b206e7

**Closed** 2018-02-11 18:25 UTC
Labels: Fixed
