### ISSUE TITLE
Can't send Mail to alt toons 

### ISSUE THREAD

**Issue by hgarner17** [elysium-project/bug-tracker#338] opened 2018-01-18 02:54 UTC
I am attempting to send an extra bag to my alt toon and when I send the bag it get this error code.

Interface\FrameXML\MailFrame.lua:623: bad argument #1 to 'strupper' (string expected, got nil) 

It occurs after I type the 2nd letter for my character and stays on the screen I type M or C or whatever the code does not pop but once I hit the vowel "A" it pops up I close it and send the item.. but I it never arrives.

I'm not sure what I need to do to fix this problem.. I guess I could trade bags with a friend who can then trade bag/item to my alt... Thanks for the help. Love Elysium Project!! 
Castius

**Comment by fulzamoth** [comment] 2018-01-19 16:05
The **Interface\FrameXML\MailFrame.lua** error is a client error caused by an _Unknown Friend_ (someone deleted a toon). It's a known issue with private servers, and is fixed by deleting any _unknowns_ in your friends list.

**Closed** 2018-02-20 17:51 UTC
Labels: Changelog, Fixed
