### ISSUE TITLE
Talents not working after ported to GM island

### ISSUE THREAD

**Issue by Osstinthax** [elysium-project/bug-tracker#387] opened 2018-02-03 03:13 UTC
Nighthaven Most recent patch

After I returned from GM islnad for a "random bot check" I noticed that my corruption skill was not receiving the benefit from "improved Corruption." Subsequently I tried to see if other talents were working like "improved Drain Soul'  which I know is based on the killing blow, and it failed to work as well. Finally I added a new point into "improved Corruption" and that talent is now affecting the spell but the other talents are still broken. Deleted WDB to no avail, GM told me to report here after a ticket was opened

**Comment by Terranzin** [comment] 2018-02-05 17:56
Regarding the use of spells, could you explain more in detail what the problem is? I´ve tested both Improved Drain soul and Improved corruption and I can´t manage to reproduce any of the errors being reported. 

Try sort it up a little bit more, showcase with a video or photo how and what is wrong.

**Comment by Osstinthax** [comment] 2018-02-07 21:32
Well I had to reset my talents man, took like a week for yall to get back. Maybe that day or even the next I could of. But as you know its pretty hard to do anything w/o talents.

**Comment by Terranzin** [comment] 2018-02-08 18:20
Well, the GM can assist resetting your talents, but if we can´t confirm it being a problem then we dont have much to fix. 

Anyway thanks for reporting issues, but I´ll close this one since it can´t be reproduced.

**Closed by Terranzin** 2018-02-08 18:20 UTC
Labels: Report Incomplete
