### ISSUE TITLE
Quest: "The God Hakkar" inconsitent behavior - Nighthaven PvP (patch 1.5)

### ISSUE THREAD

**Issue by Stormprophet** [elysium-project/bug-tracker#511] opened 2018-03-02 23:39 UTC
Following issues are common (based on 3 hours over 2 nights of attempting the encounter) occurences when attempting the quest.

1) Upon using Item: Egg of Hakkar the event will not start, merely displaying the visuals on the ground and closing the gates, but without spawning mobs.

2) The event will randomly reset, this may occur at any time.

3) Spawning of Hakkari Bloodkeeper's is incredibly irratic, sometimes spawning up to 4 at once, other times not spawning any. Spawns the non elite serpents are also subject to huge variation.

**Comment by Terranzin** [comment] 2018-03-05 07:56
Duplicate of https://github.com/elysium-project/bug-tracker/issues/367 closing this issue.

**Closed by Terranzin** 2018-03-05 07:56 UTC
Labels: Duplicate
