### ISSUE TITLE
Lupos gone after taming it.

### ISSUE THREAD

**Issue by Shuraaaa** [elysium-project/bug-tracker#372] opened 2018-01-27 12:25 UTC
Character Name: Dread
Class: Hunter
Level: 23
Race: Horde

Issue:
I was taming Lupos then after I tamed him the wolf just faded away like a ghost, was waiting for him for about 7 hours now and that happened, after coming back to my dead body an NE danced to my face and goes away. I've searched different forums about the issue but I can't find anything related to what happened. Really sucks cause using for a Level 23 like me versing 40-60 Ally/horde for the tame and an issue like this occurred to me.

**Comment by Terranzin** [comment] 2018-01-29 19:30
I´m trying to understand the problem. While you where taming "Lupos" did a alliance player kill you? You are in a alliance zone and this will certainly happen, but I´m not fully understanding exactly what the issue is about.

**Comment by Terranzin** [comment] 2018-02-08 18:21
Closing since no reaction for 10+ days

**Closed by Terranzin** 2018-02-08 18:21 UTC
Labels: Report Incomplete
