### ISSUE TITLE
Pattern: Devilsaur Gauntlets and Leggings use wrong profession

### ISSUE THREAD

**Issue by Pikseh** [elysium-project/bug-tracker#266] opened 2018-01-03 21:41 UTC
16 days ago a topic was made in here that the Devilsaur Recipes should require Dragonscale Leatherworking. This is wrong, and no evidence was provided for their claim. It should use Tribal Leatherworking, which also fits the theme correctly, since Dragonscale Leatherworking does not craft leather items, but rather craft mail items.

Evidence: http://db.vanillagaming.org/?item=15758
The description of the item reads: 
Requires Leatherworking (290)
Requires Tribal Leatherworking

This should be changed back to requiring Tribal Leatherworking ASAP.

**Comment by fulzamoth** [comment] 2018-01-04 01:28
This is a duplicate of an existing issue. Please search before adding new bug reports.

**Comment by Terranzin** [comment] 2018-01-04 08:15
https://github.com/elysium-project/bug-tracker/issues/212

**Closed by Terranzin** 2018-01-04 08:16 UTC
Labels: Duplicate
