### ISSUE TITLE
Unable to throw dynamite.

### ISSUE THREAD

**Issue by caustic00** [elysium-project/bug-tracker#315] opened 2018-01-13 11:33 UTC
When you try to use dynamite (tested with dense dynamite) you are unable to throw it. An error message pops up stating that the spell is not available to you. All other engineering items work as intended, just the dynamite is bugged. On the discord this was also confirmed with at least one other player using coarse dynamite.

**Comment by Inomares** [comment] 2018-01-13 15:56
This also occurs with Solid Dynamite (http://db.vanillagaming.org/?item=10507). Error message displayed is as follows: "The spell is not available to you" (https://i.imgur.com/85FG5gi.png)

Tried using from action bar as well as directly from bags. Relogging and/or clearing WDB does not fix the issue.

**Comment by Terranzin** [comment] 2018-01-14 20:28
Duplicate of following issue: https://github.com/elysium-project/bug-tracker/issues/317

**Closed by Terranzin** 2018-01-14 20:28 UTC
Labels: Duplicate
