### ISSUE TITLE
Missing Items after logging on

### ISSUE THREAD

**Issue by Burntmana** [elysium-project/bug-tracker#21] opened 2017-11-14 16:13 UTC
Anytime I log out then relog in I will lose items from my character

**Comment by shenna-elysium** [comment] 2017-11-14 18:00
The issue is being looked into, we're working on automatic restoration tool. Meanwhile GMs are working on manual restoration, please make a ticket in-game.

**Comment by shenna-elysium** [comment] 2017-11-14 18:02
Error appeared in the latest core update, in the character save function, fixed now tho.

**Closed** 2018-02-20 17:52 UTC
Labels: Changelog, Fixed
