### ISSUE TITLE
Reputation Prices Incorrect

### ISSUE THREAD

**Issue by StarcatAlliance** [elysium-project/bug-tracker#363] opened 2018-01-23 19:49 UTC
I recently got to exalted with Stormwind, but the prices were only reduced by 10%, instead of the usual 20%.  I opened a ticket, and a GM reset my reputation down to neutral and then back up to exalted, but this did not help.

**Comment by Noiryx** [comment] 2018-01-26 20:01
The 20% discount due to Exalted reputation is a feature that got released in 2.3 - as we are in a patch before then this is not a bug and working as intended.

Source:
http://wowwiki.wikia.com/wiki/Exalted
http://wowwiki.wikia.com/wiki/Patch_2.3

**Comment by Terranzin** [comment] 2018-01-26 20:01
Hello,

20% reduced price came in TBC and not in vanilla.

_Patch 2.3.0 (13-Nov-2007): Vendor Discounts: All vendors, flightmasters, and repairs with an associate faction now give discounts at all levels above neutral: (Friendly: 5%, Honored: 10%, Revered: 15%, Exalted: 20%).
            Previously there was a flat 10% discount starting at honored._

**Closed by Terranzin** 2018-01-26 20:01 UTC
