### ISSUE TITLE
First Aid

### ISSUE THREAD

**Issue by DreadedWarlock** [elysium-project/bug-tracker#303] opened 2018-01-10 23:43 UTC
I still have issues with First Aid on the Horde side. I cannot train Runecloth Bandages and Heavy Runecloth Bandages. A GM was able to give me Heavy Mageweave but it's grey to me now :(

**Comment by Egregious** [comment] 2018-01-11 01:18
This issue should have been fixed in conjunction with issue #261: https://github.com/elysium-project/bug-tracker/issues/261

Please let us know if the problem persists.

**Comment by Terranzin** [comment] 2018-01-12 18:38
Duplicate of https://github.com/elysium-project/bug-tracker/issues/261

**Closed by Terranzin** 2018-01-12 18:38 UTC
Labels: Duplicate
